apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-mysql
  namespace: argocd
spec:
  project: default
  source:
    chart: my-sql
    repoURL: oci://registry-1.docker.io/bitnamicharts/mysql
    targertVersion: 9.10.8
    helm:
      releaseName: my-mysql
  destination: 
    server: https://kubernetes.default.svc
    namespace: dupa