apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-mysql
  namespace: argocd
spec:
  project: default
  source:
    chart: bitnami/mysql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.10.8
    helm:
      releaseName: my-mysql
  destination: 
    server: https://kubernetes.default.svc
    namespace: dupa