apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: app
  name: app
spec:
  containers:
  - image: flask-mysql-docker-test
    name: app
    resources: {}
    imagePullPolicy: Never
    envFrom:
    - configMapRef:
        name: special-config
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
